name: Scrape daily

on:
  schedule:
    - cron: "10 3 * * *"   # 03:10 UTC (≈ 05:10 Zurich l'été)
  workflow_dispatch: {}     # bouton "Run workflow"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          # pas de cache => évite l'avertissement de lockfile manquant

      - name: Install deps
        run: |
          npm i
          npx playwright install --with-deps chromium

      - name: Run scraper
        run: node scrape.mjs
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
          AIRTABLE_BASE:  ${{ secrets.AIRTABLE_BASE }}
          AIRTABLE_TABLE: ${{ secrets.AIRTABLE_TABLE }}

      - name: Upload CSV (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: latest-csv
          path: data/latest.csv
          retention-days: 14
